### ISSUE TITLE
System must display the ranked list of traffic signals with most associated crashes (v1)

### ISSUE THREAD

**Issue by garrisonreid** [code-for-chapel-hill/CrashModel#5]
Write JavaScript script to generate a list of traffic signals ranked by most associated crashes.

**Comment by bimbashrestha** [comment]
Use this function to calculate number of crashes near traffic signal
https://github.com/code-for-chapel-hill/CrashModel/blob/dcc675107ef3e8b28a3bf13b2b73efd087a07ccb/js/geo_functions.js#L13-L21
